// ==== Base de artículos ====

const articulos = [
  {
    titulo: "La enseñanza de Majora",
    descripcion: "La lección de vida de un gran videojuego.",
    fecha: "2025-12-23",
    url: "articles/la-ensenanza-de-majora.html",
    tag: "Ensayo",
    thumb: "images/thumbnail-images/Majoras-Mask-3D-cover.png",
  },
  {
    titulo: "Reseña de Metroid Prime 4: Beyond",
    descripcion: "Una entrega adaptada a tiempos modernos.",
    fecha: "2025-12-22",
    url: "articles/resena-metroid-prime-beyond.html",
    tag: "Reseña",
    thumb: "images/thumbnail-images/Metroid-Prime-4-Beyond.png",
  },
  {
    titulo: "¡Nuevo Mega Man recién anunciado!",
    descripcion: "Gran noticia para los fans de la saga.",
    fecha: "2025-12-12",
    url: "articles/nuevo-mega-man-anunciado.html",
    tag: "Noticia",
    thumb: "images/thumbnail-images/Mega-Man-Dual-Override.png",
  },
  {
    titulo: "Grandes canciones de videojuegos",
    descripcion: "Un listado de mis canciones favoritas.",
    fecha: "2025-12-05",
    url: "articles/las-mejores-canciones-de-videojuegos.html",
    tag: "Ranking",
    thumb: "images/thumbnail-images/Music-Note.png",
  },
  {
    titulo: "La colección que llegué a tener",
    descripcion: "Un recuerdo de los juegos y consolas que perdí.",
    fecha: "2025-11-26",
    url: "articles/la-coleccion-que-perdi.html",
    tag: "Crónica",
    thumb: "images/thumbnail-images/Colección-consolas.png",
  },
  {
    titulo: "10 juegos que faltan en Nintendo Switch",
    descripcion: "Un listado de juegos que quisiera ver en la híbrida.",
    fecha: "2025-11-23",
    url: "articles/10-juegos-que-faltan-en-switch_v2.html",
    tag: "Opinión",
    thumb: "images/thumbnail-images/Nintendo-Switch.jpg",
  },
  {
    titulo: "La crisis oculta de Nintendo",
    descripcion: "Una verdad escondida detrás de sus éxitos más recientes.",
    fecha: "2025-11-20",
    url: "articles/la-crisis-oculta-de-nintendo.html",
    tag: "Análisis",
    thumb: "images/thumbnail-images/Nintendo-Switch-2-logo.png",
  },
];