// ==== Base de artículos ====

const articulos = [
  {
    titulo: "¡Rayman regresa por la puerta grande!",
    descripcion: "Se celebra su aniversario número 30.",
    fecha: "2026-02-13",
    url: "articles/rayman-anniversary-edition.html",
    tag: "Noticia",
    thumb: "images/thumbnail-images/Rayman-30th-Anniversary-Edition.jpeg",
  },
  {
    titulo: "Recuerdos perdidos: Creative Writer",
    descripcion: "La rememoración de un software olvidado.",
    fecha: "2026-02-08",
    url: "articles/rescatando-recuerdos-creative-writer.html",
    tag: "Nostalgia",
    thumb: "images/thumbnail-images/Creative-Writer.png",
  },
  {
    titulo: "El desarrollo de mi primer videojuego",
    descripcion: "La historia de cómo Ducklas llegó a ser.",
    fecha: "2026-01-20",
    url: "articles/el-desarrollo-de-ducklas.html",
    tag: "Crónica",
    thumb: "images/thumbnail-images/Ducklas.png",
  },
  {
    titulo: "El dilema de la diferenciación",
    descripcion: "Los problemas y virtudes de un principio esencial.",
    fecha: "2026-01-12",
    url: "articles/el-dilema-de-la-diferenciacion.html",
    tag: "Ensayo",
    thumb: "images/thumbnail-images/Not-Equal-To.png",
  },
  {
    titulo: "El encanto del mundo analógico",
    descripcion: "Análisis y recuerdos de una época pasada.",
    fecha: "2026-01-06",
    url: "articles/el-encanto-del-mundo-analogico.html",
    tag: "Reflexión",
    thumb: "images/thumbnail-images/Video-Game-Controller.png",
  },
  {
    titulo: "La enseñanza de Majora's Mask",
    descripcion: "Una lección de vida de un gran videojuego.",
    fecha: "2025-12-23",
    url: "articles/la-ensenanza-de-majora.html",
    tag: "Ensayo",
    thumb: "images/thumbnail-images/Majoras-Mask-3D-cover.png",
  },
  {
    titulo: "Reseña de Metroid Prime 4: Beyond",
    descripcion: "Una entrega adaptada a tiempos modernos.",
    fecha: "2025-12-22",
    url: "articles/resena-metroid-prime-beyond.html",
    tag: "Reseña",
    thumb: "images/thumbnail-images/Metroid-Prime-4-Beyond.png",
  },
  {
    titulo: "¡Nuevo Mega Man recién anunciado!",
    descripcion: "Gran noticia para los fans de la saga.",
    fecha: "2025-12-12",
    url: "articles/nuevo-mega-man-anunciado.html",
    tag: "Noticia",
    thumb: "images/thumbnail-images/Mega-Man-Dual-Override.png",
  },
  {
    titulo: "Grandes canciones de videojuegos",
    descripcion: "Un listado de mis canciones favoritas.",
    fecha: "2025-12-05",
    url: "articles/las-mejores-canciones-de-videojuegos.html",
    tag: "Ranking",
    thumb: "images/thumbnail-images/Music-Note.png",
  },
  {
    titulo: "La colección que tuve en mi poder",
    descripcion: "Un recuerdo de los juegos y consolas que perdí.",
    fecha: "2025-11-26",
    url: "articles/la-coleccion-que-perdi.html",
    tag: "Crónica",
    thumb: "images/thumbnail-images/Colección-consolas.png",
  },
  {
    titulo: "10 juegos que faltan en Nintendo Switch",
    descripcion: "Un listado de juegos que quisiera ver en la híbrida.",
    fecha: "2025-11-23",
    url: "articles/10-juegos-que-faltan-en-switch.html",
    tag: "Opinión",
    thumb: "images/thumbnail-images/Nintendo-Switch.jpg",
  },
  {
    titulo: "La crisis oculta de Nintendo",
    descripcion: "Una verdad escondida detrás de sus éxitos más recientes.",
    fecha: "2025-11-20",
    url: "articles/la-crisis-oculta-de-nintendo.html",
    tag: "Análisis",
    thumb: "images/thumbnail-images/Nintendo-Switch-2-logo.png",
  },
];